/*******************************************************************************
 *
 * Pentaho Data Profiling
 *
 * Copyright (C) 2002-2017 by Hitachi Vantara : http://www.pentaho.com
 *
 *******************************************************************************
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with
 * the License. You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 ******************************************************************************/

package org.pentaho.profiling.model.metrics.contributor.percentile;

/**
 * Created by bryan on 3/11/15.
 */
public class PercentileDefinition {
  private String namePath;
  private String nameKey;
  private double percentile;

  public PercentileDefinition() {
    this( null, null, 0 );
  }

  public PercentileDefinition( String namePath, String nameKey, double percentile ) {
    this.namePath = namePath;
    this.nameKey = nameKey;
    this.percentile = percentile;
  }

  public String getNamePath() {
    return namePath;
  }

  public void setNamePath( String namePath ) {
    this.namePath = namePath;
  }

  public String getNameKey() {
    return nameKey;
  }

  public void setNameKey( String nameKey ) {
    this.nameKey = nameKey;
  }

  public double getPercentile() {
    return percentile;
  }

  public void setPercentile( double percentile ) {
    this.percentile = percentile;
  }

  //OperatorWrap isn't helpful for autogenerated methods
  //CHECKSTYLE:OperatorWrap:OFF
  @Override public boolean equals( Object o ) {
    if ( this == o ) {
      return true;
    }
    if ( o == null || getClass() != o.getClass() ) {
      return false;
    }

    PercentileDefinition that = (PercentileDefinition) o;

    if ( Double.compare( that.percentile, percentile ) != 0 ) {
      return false;
    }
    if ( namePath != null ? !namePath.equals( that.namePath ) : that.namePath != null ) {
      return false;
    }
    return !( nameKey != null ? !nameKey.equals( that.nameKey ) : that.nameKey != null );

  }

  @Override public int hashCode() {
    int result;
    long temp;
    result = namePath != null ? namePath.hashCode() : 0;
    result = 31 * result + ( nameKey != null ? nameKey.hashCode() : 0 );
    temp = Double.doubleToLongBits( percentile );
    result = 31 * result + (int) ( temp ^ ( temp >>> 32 ) );
    return result;
  }

  @Override public String toString() {
    return "PercentileDefinition{" +
      "namePath='" + namePath + '\'' +
      ", nameKey='" + nameKey + '\'' +
      ", percentile=" + percentile +
      '}';
  }
  //CHECKSTYLE:OperatorWrap:ON
}
