/*!
 * PENTAHO CORPORATION PROPRIETARY AND CONFIDENTIAL
 *
 * Copyright 2002 - 2015 Pentaho Corporation (Pentaho). All rights reserved.
 *
 * NOTICE: All information including source code contained herein is, and
 * remains the sole property of Pentaho and its licensors. The intellectual
 * and technical concepts contained herein are proprietary and confidential
 * to, and are trade secrets of Pentaho and may be covered by U.S. and foreign
 * patents, or patents in process, and are protected by trade secret and
 * copyright laws. The receipt or possession of this source code and/or related
 * information does not convey or imply any rights to reproduce, disclose or
 * distribute its contents, or to manufacture, use, or sell anything that it
 * may describe, in whole or in part. Any reproduction, modification, distribution,
 * or public display of this information without the express written authorization
 * from Pentaho is strictly prohibited and in violation of applicable laws and
 * international treaties. Access to the source code contained herein is strictly
 * prohibited to anyone except those individuals and entities who have executed
 * confidentiality and non-disclosure agreements or other agreements with Pentaho,
 * explicitly covering such access.
 */

package com.pentaho.profiling.api.metrics.bundle;

import com.pentaho.profiling.api.classes.HasClasses;

import java.util.ArrayList;
import java.util.List;

/**
 * Created by bryan on 3/9/15.
 */
public class MetricContributorBundleImpl implements MetricContributorBundle, HasClasses {
  private String name;
  private List<Class> metricContributorClasses;

  public MetricContributorBundleImpl() {
    metricContributorClasses = new ArrayList<Class>();
  }

  @Override public List<Class> getMetricContributorClasses() {
    return metricContributorClasses;
  }

  public void setMetricContributorClasses( List<Class> metricContributorClasses ) {
    this.metricContributorClasses = metricContributorClasses;
  }

  @Override
  public String getName() {
    return name;
  }

  public void setName( String name ) {
    this.name = name;
  }

  //OperatorWrap isn't helpful for autogenerated methods
  //CHECKSTYLE:OperatorWrap:OFF
  @Override
  public boolean equals( Object o ) {
    if ( this == o ) {
      return true;
    }
    if ( o == null || getClass() != o.getClass() ) {
      return false;
    }

    MetricContributorBundleImpl that = (MetricContributorBundleImpl) o;

    if ( metricContributorClasses != null ? !metricContributorClasses.equals( that.metricContributorClasses ) :
      that.metricContributorClasses != null ) {
      return false;
    }
    if ( name != null ? !name.equals( that.name ) : that.name != null ) {
      return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int result = name != null ? name.hashCode() : 0;
    result = 31 * result + ( metricContributorClasses != null ? metricContributorClasses.hashCode() : 0 );
    return result;
  }

  @Override public String toString() {
    return "MetricContributorBundleImpl{" +
      "name='" + name + '\'' +
      ", metricContributorClasses=" + metricContributorClasses +
      '}';
  }

  @Override public List<Class> getClasses() {
    return metricContributorClasses;
  }
  //CHECKSTYLE:OperatorWrap:ON
}
