/*******************************************************************************
 *
 * Pentaho Data Profiling
 *
 * Copyright (C) 2002-2015 by Pentaho : http://www.pentaho.com
 *
 *******************************************************************************
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with
 * the License. You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 ******************************************************************************/

package org.pentaho.profiling.api.metrics.bundle;

import org.pentaho.profiling.api.classes.HasClasses;

import java.util.ArrayList;
import java.util.List;

/**
 * Created by bryan on 3/9/15.
 */
public class MetricContributorBundleImpl implements MetricContributorBundle, HasClasses {
  private String name;
  private List<Class> classes;

  public MetricContributorBundleImpl() {
    classes = new ArrayList<Class>();
  }

  @Override public List<Class> getClasses() {
    return classes;
  }

  public void setClasses( List<Class> classes ) {
    this.classes = classes;
  }

  @Override
  public String getName() {
    return name;
  }

  public void setName( String name ) {
    this.name = name;
  }

  //OperatorWrap isn't helpful for autogenerated methods
  //CHECKSTYLE:OperatorWrap:OFF

  @Override public boolean equals( Object o ) {
    if ( this == o ) {
      return true;
    }
    if ( o == null || getClass() != o.getClass() ) {
      return false;
    }

    MetricContributorBundleImpl that = (MetricContributorBundleImpl) o;

    if ( name != null ? !name.equals( that.name ) : that.name != null ) {
      return false;
    }
    return !( classes != null ? !classes.equals( that.classes ) : that.classes != null );

  }

  @Override public int hashCode() {
    int result = name != null ? name.hashCode() : 0;
    result = 31 * result + ( classes != null ? classes.hashCode() : 0 );
    return result;
  }

  @Override public String toString() {
    return "MetricContributorBundleImpl{" +
      "name='" + name + '\'' +
      ", classes=" + classes +
      '}';
  }

  //CHECKSTYLE:OperatorWrap:ON
}
