/*******************************************************************************
 *
 * Pentaho Data Profiling
 *
 * Copyright (C) 2002-2015 by Pentaho : http://www.pentaho.com
 *
 *******************************************************************************
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with
 * the License. You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 ******************************************************************************/

package org.pentaho.profiling.api.dto;

import org.pentaho.profiling.api.ProfileFieldValueType;
import org.pentaho.profiling.api.ValueTypeMetrics;

import java.util.Map;

/**
 * Created by bryan on 5/8/15.
 */
public class ProfileFieldValueTypeDTO implements ProfileFieldValueType {
  private String typeName;
  private Long count;
  private Map<String, ValueTypeMetrics> valueTypeMetricsMap;

  public ProfileFieldValueTypeDTO() {

  }

  public ProfileFieldValueTypeDTO( ProfileFieldValueType profileFieldValueType ) {
    this.typeName = profileFieldValueType.getTypeName();
    this.count = profileFieldValueType.getCount();
    this.valueTypeMetricsMap = profileFieldValueType.getValueTypeMetricsMap();
  }

  @Override public String getTypeName() {
    return typeName;
  }

  public void setTypeName( String typeName ) {
    this.typeName = typeName;
  }

  @Override public Long getCount() {
    return count;
  }

  public void setCount( Long count ) {
    this.count = count;
  }

  @Override public Map<String, ValueTypeMetrics> getValueTypeMetricsMap() {
    return valueTypeMetricsMap;
  }

  public void setValueTypeMetricsMap(
    Map<String, ValueTypeMetrics> valueTypeMetricsMap ) {
    this.valueTypeMetricsMap = valueTypeMetricsMap;
  }

  @Override public ValueTypeMetrics getValueTypeMetrics( String name ) {
    return valueTypeMetricsMap.get( name );
  }

  @Override public Object clone() {
    return new ProfileFieldValueTypeDTO( this );
  }

  //OperatorWrap isn't helpful for autogenerated methods
  //CHECKSTYLE:OperatorWrap:OFF
  @Override public boolean equals( Object o ) {
    if ( this == o ) {
      return true;
    }
    if ( o == null || getClass() != o.getClass() ) {
      return false;
    }

    ProfileFieldValueTypeDTO that = (ProfileFieldValueTypeDTO) o;

    if ( typeName != null ? !typeName.equals( that.typeName ) : that.typeName != null ) {
      return false;
    }
    if ( count != null ? !count.equals( that.count ) : that.count != null ) {
      return false;
    }
    return !( valueTypeMetricsMap != null ? !valueTypeMetricsMap.equals( that.valueTypeMetricsMap ) :
      that.valueTypeMetricsMap != null );

  }

  @Override public int hashCode() {
    int result = typeName != null ? typeName.hashCode() : 0;
    result = 31 * result + ( count != null ? count.hashCode() : 0 );
    result = 31 * result + ( valueTypeMetricsMap != null ? valueTypeMetricsMap.hashCode() : 0 );
    return result;
  }

  @Override public String toString() {
    return "ProfileFieldValueTypeDTO{" +
      "typeName='" + typeName + '\'' +
      ", count=" + count +
      ", valueTypeMetricsMap=" + valueTypeMetricsMap +
      '}';
  }
  //CHECKSTYLE:OperatorWrap:ON
}
