/*******************************************************************************
 *
 * Pentaho Data Profiling
 *
 * Copyright (C) 2002-2015 by Pentaho : http://www.pentaho.com
 *
 *******************************************************************************
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with
 * the License. You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 ******************************************************************************/

package org.pentaho.profiling.services;

import org.pentaho.profiling.api.metrics.field.DataSourceFieldValue;

import java.util.List;

/**
 * Created by bryan on 3/26/15.
 */
public class StreamingRecordWrapper {
  private String profileId;
  private List<DataSourceFieldValue> dataSourceFieldValues;

  public StreamingRecordWrapper() {
    this( null, null );
  }

  public StreamingRecordWrapper( String profileId,
                                 List<DataSourceFieldValue> dataSourceFieldValues ) {
    this.profileId = profileId;
    this.dataSourceFieldValues = dataSourceFieldValues;
  }

  public String getProfileId() {
    return profileId;
  }

  public void setProfileId( String profileId ) {
    this.profileId = profileId;
  }

  public List<DataSourceFieldValue> getDataSourceFieldValues() {
    return dataSourceFieldValues;
  }

  public void setDataSourceFieldValues( List<DataSourceFieldValue> dataSourceFieldValues ) {
    this.dataSourceFieldValues = dataSourceFieldValues;
  }

  //OperatorWrap isn't helpful for autogenerated methods
  //CHECKSTYLE:OperatorWrap:OFF
  @Override public boolean equals( Object o ) {
    if ( this == o ) {
      return true;
    }
    if ( o == null || getClass() != o.getClass() ) {
      return false;
    }

    StreamingRecordWrapper that = (StreamingRecordWrapper) o;

    if ( profileId != null ? !profileId.equals( that.profileId ) : that.profileId != null ) {
      return false;
    }
    return !( dataSourceFieldValues != null ? !dataSourceFieldValues.equals( that.dataSourceFieldValues ) :
      that.dataSourceFieldValues != null );

  }

  @Override public int hashCode() {
    int result = profileId != null ? profileId.hashCode() : 0;
    result = 31 * result + ( dataSourceFieldValues != null ? dataSourceFieldValues.hashCode() : 0 );
    return result;
  }

  @Override public String toString() {
    return "StreamingRecordWrapper{" +
      "profileId='" + profileId + '\'' +
      ", dataSourceFieldValues=" + dataSourceFieldValues +
      '}';
  }
  //CHECKSTYLE:OperatorWrap:ON
}
