/*******************************************************************************
 *
 * Pentaho Data Profiling
 *
 * Copyright (C) 2002-2015 by Pentaho : http://www.pentaho.com
 *
 *******************************************************************************
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with
 * the License. You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 ******************************************************************************/

package org.pentaho.profiling.rest.doc;

/**
 * Created by bryan on 4/6/15.
 */
public class EndpointExample {
  private String url;
  private String body;
  private String exampleReturn;

  public EndpointExample() {
    this( null, null, null );
  }

  public EndpointExample( String url, String body, String exampleReturn ) {
    this.url = url;
    this.body = body;
    this.exampleReturn = exampleReturn;
  }

  public String getUrl() {
    return url;
  }

  public void setUrl( String url ) {
    this.url = url;
  }

  public String getBody() {
    return body;
  }

  public void setBody( String body ) {
    this.body = body;
  }

  public String getExampleReturn() {
    return exampleReturn;
  }

  public void setExampleReturn( String exampleReturn ) {
    this.exampleReturn = exampleReturn;
  }

  //OperatorWrap isn't helpful for autogenerated methods
  //CHECKSTYLE:OperatorWrap:OFF
  @Override public boolean equals( Object o ) {
    if ( this == o ) {
      return true;
    }
    if ( o == null || getClass() != o.getClass() ) {
      return false;
    }

    EndpointExample that = (EndpointExample) o;

    if ( url != null ? !url.equals( that.url ) : that.url != null ) {
      return false;
    }
    if ( body != null ? !body.equals( that.body ) : that.body != null ) {
      return false;
    }
    return !( exampleReturn != null ? !exampleReturn.equals( that.exampleReturn ) : that.exampleReturn != null );

  }

  @Override public int hashCode() {
    int result = url != null ? url.hashCode() : 0;
    result = 31 * result + ( body != null ? body.hashCode() : 0 );
    result = 31 * result + ( exampleReturn != null ? exampleReturn.hashCode() : 0 );
    return result;
  }

  @Override public String toString() {
    return "EndpointExample{" +
      "url='" + url + '\'' +
      ", body='" + body + '\'' +
      ", exampleReturn='" + exampleReturn + '\'' +
      '}';
  }
  //CHECKSTYLE:OperatorWrap:ON
}
