/*!
 * PENTAHO CORPORATION PROPRIETARY AND CONFIDENTIAL
 *
 * Copyright 2002 - 2015 Pentaho Corporation (Pentaho). All rights reserved.
 *
 * NOTICE: All information including source code contained herein is, and
 * remains the sole property of Pentaho and its licensors. The intellectual
 * and technical concepts contained herein are proprietary and confidential
 * to, and are trade secrets of Pentaho and may be covered by U.S. and foreign
 * patents, or patents in process, and are protected by trade secret and
 * copyright laws. The receipt or possession of this source code and/or related
 * information does not convey or imply any rights to reproduce, disclose or
 * distribute its contents, or to manufacture, use, or sell anything that it
 * may describe, in whole or in part. Any reproduction, modification, distribution,
 * or public display of this information without the express written authorization
 * from Pentaho is strictly prohibited and in violation of applicable laws and
 * international treaties. Access to the source code contained herein is strictly
 * prohibited to anyone except those individuals and entities who have executed
 * confidentiality and non-disclosure agreements or other agreements with Pentaho,
 * explicitly covering such access.
 */

package com.pentaho.profiling.api.metrics;

import java.util.ArrayList;
import java.util.List;

/**
 * Created by bryan on 3/11/15.
 */
public class MetricContributors {
  private List<MetricContributor> metricContributors;
  private List<MetricManagerContributor> metricManagerContributors;

  public MetricContributors() {
    this( null, null );
  }

  public MetricContributors( List<MetricContributor> metricContributors,
                             List<MetricManagerContributor> metricManagerContributors ) {
    this.metricContributors = metricContributors;
    this.metricManagerContributors = metricManagerContributors;
  }

  public List<MetricContributor> getMetricContributors() {
    return metricContributors;
  }

  public void setMetricContributors( List<MetricContributor> metricContributors ) {
    this.metricContributors = metricContributors;
  }

  public List<MetricManagerContributor> getMetricManagerContributors() {
    return metricManagerContributors;
  }

  public void setMetricManagerContributors( List<MetricManagerContributor> metricManagerContributors ) {
    this.metricManagerContributors = metricManagerContributors;
  }

  public void add( MetricContributors other ) {
    if ( other != null ) {
      if ( this.metricContributors == null ) {
        this.metricContributors = new ArrayList<MetricContributor>();
      }
      if ( this.metricManagerContributors == null ) {
        this.metricManagerContributors = new ArrayList<MetricManagerContributor>();
      }
      if ( other.metricContributors != null ) {
        this.metricContributors.addAll( other.metricContributors );
      }
      if ( other.metricManagerContributors != null ) {
        this.metricManagerContributors.addAll( other.metricManagerContributors );
      }
    }
  }

  //OperatorWrap isn't helpful for autogenerated methods
  //CHECKSTYLE:OperatorWrap:OFF
  @Override
  public boolean equals( Object o ) {
    if ( this == o ) {
      return true;
    }
    if ( o == null || getClass() != o.getClass() ) {
      return false;
    }

    MetricContributors that = (MetricContributors) o;

    if ( metricContributors != null ? !metricContributors.equals( that.metricContributors ) :
      that.metricContributors != null ) {
      return false;
    }
    if ( metricManagerContributors != null ? !metricManagerContributors.equals( that.metricManagerContributors ) :
      that.metricManagerContributors != null ) {
      return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int result = metricContributors != null ? metricContributors.hashCode() : 0;
    result = 31 * result + ( metricManagerContributors != null ? metricManagerContributors.hashCode() : 0 );
    return result;
  }

  @Override public String toString() {
    return "MetricContributors{" +
      "metricContributors=" + metricContributors +
      ", metricManagerContributors=" + metricManagerContributors +
      '}';
  }
  //CHECKSTYLE:OperatorWrap:ON
}
