/*******************************************************************************
 *
 * Pentaho Data Profiling
 *
 * Copyright (C) 2002-2015 by Pentaho : http://www.pentaho.com
 *
 *******************************************************************************
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with
 * the License. You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 ******************************************************************************/

package org.pentaho.profiling.api.metrics;

import java.util.ArrayList;
import java.util.List;

/**
 * Created by bryan on 3/11/15.
 */
public class MetricContributors {
  private List<MetricContributor> metricContributors;
  private List<MetricManagerContributor> metricManagerContributors;

  public MetricContributors() {
    this( new ArrayList<MetricContributor>(), new ArrayList<MetricManagerContributor>() );
  }

  public MetricContributors( List<MetricContributor> metricContributors,
                             List<MetricManagerContributor> metricManagerContributors ) {
    this.metricContributors = metricContributors;
    this.metricManagerContributors = metricManagerContributors;
  }

  public List<MetricContributor> getMetricContributors() {
    return metricContributors;
  }

  public void setMetricContributors( List<MetricContributor> metricContributors ) {
    this.metricContributors = metricContributors;
  }

  public List<MetricManagerContributor> getMetricManagerContributors() {
    return metricManagerContributors;
  }

  public void setMetricManagerContributors( List<MetricManagerContributor> metricManagerContributors ) {
    this.metricManagerContributors = metricManagerContributors;
  }

  public void add( MetricContributors other ) {
    if ( other != null ) {
      if ( this.metricContributors == null ) {
        this.metricContributors = new ArrayList<MetricContributor>();
      }
      if ( this.metricManagerContributors == null ) {
        this.metricManagerContributors = new ArrayList<MetricManagerContributor>();
      }
      if ( other.metricContributors != null ) {
        this.metricContributors.addAll( other.metricContributors );
      }
      if ( other.metricManagerContributors != null ) {
        this.metricManagerContributors.addAll( other.metricManagerContributors );
      }
    }
  }

  //OperatorWrap isn't helpful for autogenerated methods
  //CHECKSTYLE:OperatorWrap:OFF
  @Override
  public boolean equals( Object o ) {
    if ( this == o ) {
      return true;
    }
    if ( o == null || getClass() != o.getClass() ) {
      return false;
    }

    MetricContributors that = (MetricContributors) o;

    if ( metricContributors != null ? !metricContributors.equals( that.metricContributors ) :
      that.metricContributors != null ) {
      return false;
    }
    if ( metricManagerContributors != null ? !metricManagerContributors.equals( that.metricManagerContributors ) :
      that.metricManagerContributors != null ) {
      return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int result = metricContributors != null ? metricContributors.hashCode() : 0;
    result = 31 * result + ( metricManagerContributors != null ? metricManagerContributors.hashCode() : 0 );
    return result;
  }

  @Override public String toString() {
    return "MetricContributors{" +
      "metricContributors=" + metricContributors +
      ", metricManagerContributors=" + metricManagerContributors +
      '}';
  }
  //CHECKSTYLE:OperatorWrap:ON
}
