/*******************************************************************************
 *
 * Pentaho Data Profiling
 *
 * Copyright (C) 2002-2015 by Pentaho : http://www.pentaho.com
 *
 *******************************************************************************
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with
 * the License. You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 ******************************************************************************/

package org.pentaho.profiling.rest.doc;

/**
 * Created by bryan on 4/6/15.
 */
public class EndpointReturnCode {
  private int status;
  private String reason;

  public EndpointReturnCode() {
    this( -1, null );
  }

  public EndpointReturnCode( int status, String reason ) {
    this.status = status;
    this.reason = reason;
  }

  public int getStatus() {
    return status;
  }

  public void setStatus( int status ) {
    this.status = status;
  }

  public String getReason() {
    return reason;
  }

  public void setReason( String reason ) {
    this.reason = reason;
  }

  //OperatorWrap isn't helpful for autogenerated methods
  //CHECKSTYLE:OperatorWrap:OFF
  @Override public boolean equals( Object o ) {
    if ( this == o ) {
      return true;
    }
    if ( o == null || getClass() != o.getClass() ) {
      return false;
    }

    EndpointReturnCode that = (EndpointReturnCode) o;

    if ( status != that.status ) {
      return false;
    }
    return !( reason != null ? !reason.equals( that.reason ) : that.reason != null );

  }

  @Override public int hashCode() {
    int result = status;
    result = 31 * result + ( reason != null ? reason.hashCode() : 0 );
    return result;
  }

  @Override public String toString() {
    return "EndpointReturnCode{" +
      "status=" + status +
      ", reason='" + reason + '\'' +
      '}';
  }
  //CHECKSTYLE:OperatorWrap:ON
}
