/*!
 * PENTAHO CORPORATION PROPRIETARY AND CONFIDENTIAL
 *
 * Copyright 2002 - 2015 Pentaho Corporation (Pentaho). All rights reserved.
 *
 * NOTICE: All information including source code contained herein is, and
 * remains the sole property of Pentaho and its licensors. The intellectual
 * and technical concepts contained herein are proprietary and confidential
 * to, and are trade secrets of Pentaho and may be covered by U.S. and foreign
 * patents, or patents in process, and are protected by trade secret and
 * copyright laws. The receipt or possession of this source code and/or related
 * information does not convey or imply any rights to reproduce, disclose or
 * distribute its contents, or to manufacture, use, or sell anything that it
 * may describe, in whole or in part. Any reproduction, modification, distribution,
 * or public display of this information without the express written authorization
 * from Pentaho is strictly prohibited and in violation of applicable laws and
 * international treaties. Access to the source code contained herein is strictly
 * prohibited to anyone except those individuals and entities who have executed
 * confidentiality and non-disclosure agreements or other agreements with Pentaho,
 * explicitly covering such access.
 */

package com.pentaho.profiling.api;

import com.pentaho.profiling.api.datasource.DataSourceReference;
import com.pentaho.profiling.api.metrics.MetricContributors;

/**
 * Created by bryan on 3/9/15.
 */
public class ProfileCreateRequest {
  private DataSourceReference dataSourceReference;
  private MetricContributors metricContributors;

  public ProfileCreateRequest() {
    this( null, null );
  }

  public ProfileCreateRequest( DataSourceReference dataSourceReference,
                               MetricContributors metricContributors ) {
    this.dataSourceReference = dataSourceReference;
    this.metricContributors = metricContributors;
  }

  public DataSourceReference getDataSourceReference() {
    return dataSourceReference;
  }

  public void setDataSourceReference( DataSourceReference dataSourceReference ) {
    this.dataSourceReference = dataSourceReference;
  }

  public MetricContributors getMetricContributors() {
    return metricContributors;
  }

  public void setMetricContributors( MetricContributors metricContributors ) {
    this.metricContributors = metricContributors;
  }

  //OperatorWrap isn't helpful for autogenerated methods
  //CHECKSTYLE:OperatorWrap:OFF
  @Override
  public boolean equals( Object o ) {
    if ( this == o ) {
      return true;
    }
    if ( o == null || getClass() != o.getClass() ) {
      return false;
    }

    ProfileCreateRequest that = (ProfileCreateRequest) o;

    if ( dataSourceReference != null ? !dataSourceReference.equals( that.dataSourceReference ) :
      that.dataSourceReference != null ) {
      return false;
    }
    if ( metricContributors != null ? !metricContributors.equals( that.metricContributors ) :
      that.metricContributors != null ) {
      return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int result = dataSourceReference != null ? dataSourceReference.hashCode() : 0;
    result = 31 * result + ( metricContributors != null ? metricContributors.hashCode() : 0 );
    return result;
  }

  @Override public String toString() {
    return "ProfileCreateRequest{" +
      "dataSourceReference=" + dataSourceReference +
      ", metricContributors=" + metricContributors +
      '}';
  }
  //CHECKSTYLE:OperatorWrap:ON
}
