/*******************************************************************************
 *
 * Pentaho Data Profiling
 *
 * Copyright (C) 2002-2017 by Hitachi Vantara : http://www.pentaho.com
 *
 *******************************************************************************
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with
 * the License. You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 ******************************************************************************/

package org.pentaho.profiling.api.doc.rest;


import com.fasterxml.jackson.databind.ObjectMapper;

/**
 * Created by bryan on 4/7/15.
 */
public class DocEndpointImpl implements DocEndpoint {
  private String address;
  private Object endpointBean;
  private ObjectMapper objectMapper;

  public DocEndpointImpl() {
    this( null, null, null );
  }

  public DocEndpointImpl( String address, Object endpointBean, ObjectMapper objectMapper ) {
    this.address = address;
    this.endpointBean = endpointBean;
    this.objectMapper = objectMapper;
  }

  public Object getEndpointBean() {
    return endpointBean;
  }

  public void setEndpointBean( Object endpointBean ) {
    this.endpointBean = endpointBean;
  }

  public ObjectMapper getObjectMapper() {
    return objectMapper;
  }

  public void setObjectMapper( ObjectMapper objectMapper ) {
    this.objectMapper = objectMapper;
  }

  public String getAddress() {
    return address;
  }

  public void setAddress( String address ) {
    this.address = address;
  }

  //OperatorWrap isn't helpful for autogenerated methods
  //CHECKSTYLE:OperatorWrap:OFF
  @Override public boolean equals( Object o ) {
    if ( this == o ) {
      return true;
    }
    if ( o == null || getClass() != o.getClass() ) {
      return false;
    }

    DocEndpointImpl that = (DocEndpointImpl) o;

    if ( address != null ? !address.equals( that.address ) : that.address != null ) {
      return false;
    }
    if ( endpointBean != null ? !endpointBean.equals( that.endpointBean ) : that.endpointBean != null ) {
      return false;
    }
    return !( objectMapper != null ? !objectMapper.equals( that.objectMapper ) : that.objectMapper != null );

  }

  @Override public int hashCode() {
    int result = address != null ? address.hashCode() : 0;
    result = 31 * result + ( endpointBean != null ? endpointBean.hashCode() : 0 );
    result = 31 * result + ( objectMapper != null ? objectMapper.hashCode() : 0 );
    return result;
  }

  @Override public String toString() {
    return "DocEndpointImpl{" +
      "address='" + address + '\'' +
      ", endpointBean=" + endpointBean +
      ", objectMapper=" + objectMapper +
      '}';
  }
  //CHECKSTYLE:OperatorWrap:ON
}
