/*******************************************************************************
 *
 * Pentaho Data Profiling
 *
 * Copyright (C) 2002-2017 by Hitachi Vantara : http://www.pentaho.com
 *
 *******************************************************************************
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with
 * the License. You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 ******************************************************************************/

package org.pentaho.profiling.api.doc.rest;

/**
 * Created by bryan on 4/6/15.
 */
public class DocParameter {
  private String name;
  private String comment;

  public DocParameter() {
    this( null, null );
  }

  public DocParameter( String name, String comment ) {
    this.name = name;
    this.comment = comment;
  }

  public String getName() {
    return name;
  }

  public void setName( String name ) {
    this.name = name;
  }

  public String getComment() {
    return comment;
  }

  public void setComment( String comment ) {
    this.comment = comment;
  }

  //OperatorWrap isn't helpful for autogenerated methods
  //CHECKSTYLE:OperatorWrap:OFF
  @Override public boolean equals( Object o ) {
    if ( this == o ) {
      return true;
    }
    if ( o == null || getClass() != o.getClass() ) {
      return false;
    }

    DocParameter that = (DocParameter) o;

    if ( name != null ? !name.equals( that.name ) : that.name != null ) {
      return false;
    }
    return !( comment != null ? !comment.equals( that.comment ) : that.comment != null );

  }

  @Override public int hashCode() {
    int result = name != null ? name.hashCode() : 0;
    result = 31 * result + ( comment != null ? comment.hashCode() : 0 );
    return result;
  }

  @Override public String toString() {
    return "DocParameter{" +
      "name='" + name + '\'' +
      ", comment='" + comment + '\'' +
      '}';
  }
  //CHECKSTYLE:OperatorWrap:ON
}
