/*!
 * PENTAHO CORPORATION PROPRIETARY AND CONFIDENTIAL
 *
 * Copyright 2002 - 2015 Pentaho Corporation (Pentaho). All rights reserved.
 *
 * NOTICE: All information including source code contained herein is, and
 * remains the sole property of Pentaho and its licensors. The intellectual
 * and technical concepts contained herein are proprietary and confidential
 * to, and are trade secrets of Pentaho and may be covered by U.S. and foreign
 * patents, or patents in process, and are protected by trade secret and
 * copyright laws. The receipt or possession of this source code and/or related
 * information does not convey or imply any rights to reproduce, disclose or
 * distribute its contents, or to manufacture, use, or sell anything that it
 * may describe, in whole or in part. Any reproduction, modification, distribution,
 * or public display of this information without the express written authorization
 * from Pentaho is strictly prohibited and in violation of applicable laws and
 * international treaties. Access to the source code contained herein is strictly
 * prohibited to anyone except those individuals and entities who have executed
 * confidentiality and non-disclosure agreements or other agreements with Pentaho,
 * explicitly covering such access.
 */

package com.pentaho.profiling.model.metrics.contributor.percentile;

/**
 * Created by bryan on 3/11/15.
 */
public class PercentileDefinition {
  private String namePath;
  private String nameKey;
  private double percentile;

  public PercentileDefinition() {
    this( null, null, 0 );
  }

  public PercentileDefinition( String namePath, String nameKey, double percentile ) {
    this.namePath = namePath;
    this.nameKey = nameKey;
    this.percentile = percentile;
  }

  public String getNamePath() {
    return namePath;
  }

  public void setNamePath( String namePath ) {
    this.namePath = namePath;
  }

  public String getNameKey() {
    return nameKey;
  }

  public void setNameKey( String nameKey ) {
    this.nameKey = nameKey;
  }

  public double getPercentile() {
    return percentile;
  }

  public void setPercentile( double percentile ) {
    this.percentile = percentile;
  }

  //OperatorWrap isn't helpful for autogenerated methods
  //CHECKSTYLE:OperatorWrap:OFF
  @Override public boolean equals( Object o ) {
    if ( this == o ) {
      return true;
    }
    if ( o == null || getClass() != o.getClass() ) {
      return false;
    }

    PercentileDefinition that = (PercentileDefinition) o;

    if ( Double.compare( that.percentile, percentile ) != 0 ) {
      return false;
    }
    if ( namePath != null ? !namePath.equals( that.namePath ) : that.namePath != null ) {
      return false;
    }
    return !( nameKey != null ? !nameKey.equals( that.nameKey ) : that.nameKey != null );

  }

  @Override public int hashCode() {
    int result;
    long temp;
    result = namePath != null ? namePath.hashCode() : 0;
    result = 31 * result + ( nameKey != null ? nameKey.hashCode() : 0 );
    temp = Double.doubleToLongBits( percentile );
    result = 31 * result + (int) ( temp ^ ( temp >>> 32 ) );
    return result;
  }

  @Override public String toString() {
    return "PercentileDefinition{" +
      "namePath='" + namePath + '\'' +
      ", nameKey='" + nameKey + '\'' +
      ", percentile=" + percentile +
      '}';
  }
  //CHECKSTYLE:OperatorWrap:ON
}
