/*!
 * PENTAHO CORPORATION PROPRIETARY AND CONFIDENTIAL
 *
 * Copyright 2002 - 2015 Pentaho Corporation (Pentaho). All rights reserved.
 *
 * NOTICE: All information including source code contained herein is, and
 * remains the sole property of Pentaho and its licensors. The intellectual
 * and technical concepts contained herein are proprietary and confidential
 * to, and are trade secrets of Pentaho and may be covered by U.S. and foreign
 * patents, or patents in process, and are protected by trade secret and
 * copyright laws. The receipt or possession of this source code and/or related
 * information does not convey or imply any rights to reproduce, disclose or
 * distribute its contents, or to manufacture, use, or sell anything that it
 * may describe, in whole or in part. Any reproduction, modification, distribution,
 * or public display of this information without the express written authorization
 * from Pentaho is strictly prohibited and in violation of applicable laws and
 * international treaties. Access to the source code contained herein is strictly
 * prohibited to anyone except those individuals and entities who have executed
 * confidentiality and non-disclosure agreements or other agreements with Pentaho,
 * explicitly covering such access.
 */

package com.pentaho.profiling.api.configuration;

import com.pentaho.profiling.api.metrics.MetricContributors;

/**
 * Created by bryan on 4/10/15.
 */
public class ProfileConfiguration {
  private DataSourceMetadata dataSourceMetadata;
  private String configName;
  private MetricContributors metricContributors;

  public ProfileConfiguration() {
    this( null, null, null );
  }

  public ProfileConfiguration( DataSourceMetadata dataSourceMetadata,
                               String configName, MetricContributors metricContributors ) {
    this.dataSourceMetadata = dataSourceMetadata;
    this.configName = configName;
    this.metricContributors = metricContributors;
  }

  public DataSourceMetadata getDataSourceMetadata() {
    return dataSourceMetadata;
  }

  public void setDataSourceMetadata( DataSourceMetadata dataSourceMetadata ) {
    this.dataSourceMetadata = dataSourceMetadata;
  }

  public MetricContributors getMetricContributors() {
    return metricContributors;
  }

  public void setMetricContributors( MetricContributors metricContributors ) {
    this.metricContributors = metricContributors;
  }

  public String getConfigName() {
    return configName;
  }

  public void setConfigName( String configName ) {
    this.configName = configName;
  }

  //OperatorWrap isn't helpful for autogenerated methods
  //CHECKSTYLE:OperatorWrap:OFF

  @Override public boolean equals( Object o ) {
    if ( this == o ) {
      return true;
    }
    if ( o == null || getClass() != o.getClass() ) {
      return false;
    }

    ProfileConfiguration that = (ProfileConfiguration) o;

    if ( dataSourceMetadata != null ? !dataSourceMetadata.equals( that.dataSourceMetadata ) :
      that.dataSourceMetadata != null ) {
      return false;
    }
    if ( configName != null ? !configName.equals( that.configName ) : that.configName != null ) {
      return false;
    }
    return !( metricContributors != null ? !metricContributors.equals( that.metricContributors ) :
      that.metricContributors != null );

  }

  @Override public int hashCode() {
    int result = dataSourceMetadata != null ? dataSourceMetadata.hashCode() : 0;
    result = 31 * result + ( configName != null ? configName.hashCode() : 0 );
    result = 31 * result + ( metricContributors != null ? metricContributors.hashCode() : 0 );
    return result;
  }

  @Override public String toString() {
    return "ProfileConfiguration{" +
      "dataSourceMetadata=" + dataSourceMetadata +
      ", configName='" + configName + '\'' +
      ", metricContributors=" + metricContributors +
      '}';
  }
  //CHECKSTYLE:OperatorWrap:ON
}
