/*!
 * PENTAHO CORPORATION PROPRIETARY AND CONFIDENTIAL
 *
 * Copyright 2002 - 2015 Pentaho Corporation (Pentaho). All rights reserved.
 *
 * NOTICE: All information including source code contained herein is, and
 * remains the sole property of Pentaho and its licensors. The intellectual
 * and technical concepts contained herein are proprietary and confidential
 * to, and are trade secrets of Pentaho and may be covered by U.S. and foreign
 * patents, or patents in process, and are protected by trade secret and
 * copyright laws. The receipt or possession of this source code and/or related
 * information does not convey or imply any rights to reproduce, disclose or
 * distribute its contents, or to manufacture, use, or sell anything that it
 * may describe, in whole or in part. Any reproduction, modification, distribution,
 * or public display of this information without the express written authorization
 * from Pentaho is strictly prohibited and in violation of applicable laws and
 * international treaties. Access to the source code contained herein is strictly
 * prohibited to anyone except those individuals and entities who have executed
 * confidentiality and non-disclosure agreements or other agreements with Pentaho,
 * explicitly covering such access.
 */

package com.pentaho.profiling.services;

import javax.xml.bind.annotation.XmlRootElement;

/**
 * Created by bryan on 3/5/15.
 */
@XmlRootElement
public class AggregateAddChildWrapper {
  private String profileId;
  private String childProfileId;

  public AggregateAddChildWrapper() {
    this( null, null );
  }

  public AggregateAddChildWrapper( String profileId, String childProfileId ) {
    this.profileId = profileId;
    this.childProfileId = childProfileId;
  }

  public String getChildProfileId() {

    return childProfileId;
  }

  public void setChildProfileId( String childProfileId ) {
    this.childProfileId = childProfileId;
  }

  public String getProfileId() {
    return profileId;
  }

  public void setProfileId( String profileId ) {
    this.profileId = profileId;
  }

  //OperatorWrap isn't helpful for autogenerated methods
  //CHECKSTYLE:OperatorWrap:OFF
  @Override public String toString() {
    return "AggregateAddChildWrapper{" +
      "profileId='" + profileId + '\'' +
      ", childProfileId='" + childProfileId + '\'' +
      '}';
  }

  @Override
  public boolean equals( Object o ) {
    if ( this == o ) {
      return true;
    }
    if ( o == null || getClass() != o.getClass() ) {
      return false;
    }

    AggregateAddChildWrapper that = (AggregateAddChildWrapper) o;

    if ( childProfileId != null ? !childProfileId.equals( that.childProfileId ) : that.childProfileId != null ) {
      return false;
    }
    if ( profileId != null ? !profileId.equals( that.profileId ) : that.profileId != null ) {
      return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int result = profileId != null ? profileId.hashCode() : 0;
    result = 31 * result + ( childProfileId != null ? childProfileId.hashCode() : 0 );
    return result;
  }
  //CHECKSTYLE:OperatorWrap:ON
}
