/*!
 * PENTAHO CORPORATION PROPRIETARY AND CONFIDENTIAL
 *
 * Copyright 2002 - 2015 Pentaho Corporation (Pentaho). All rights reserved.
 *
 * NOTICE: All information including source code contained herein is, and
 * remains the sole property of Pentaho and its licensors. The intellectual
 * and technical concepts contained herein are proprietary and confidential
 * to, and are trade secrets of Pentaho and may be covered by U.S. and foreign
 * patents, or patents in process, and are protected by trade secret and
 * copyright laws. The receipt or possession of this source code and/or related
 * information does not convey or imply any rights to reproduce, disclose or
 * distribute its contents, or to manufacture, use, or sell anything that it
 * may describe, in whole or in part. Any reproduction, modification, distribution,
 * or public display of this information without the express written authorization
 * from Pentaho is strictly prohibited and in violation of applicable laws and
 * international treaties. Access to the source code contained herein is strictly
 * prohibited to anyone except those individuals and entities who have executed
 * confidentiality and non-disclosure agreements or other agreements with Pentaho,
 * explicitly covering such access.
 */

package com.pentaho.profiling.api.doc.rest;

import org.codehaus.jackson.map.ObjectMapper;

/**
 * Created by bryan on 4/7/15.
 */
public class DocEndpointImpl implements DocEndpoint {
  private String address;
  private Object endpointBean;
  private ObjectMapper objectMapper;

  public DocEndpointImpl() {
    this( null, null, null );
  }

  public DocEndpointImpl( String address, Object endpointBean, ObjectMapper objectMapper ) {
    this.address = address;
    this.endpointBean = endpointBean;
    this.objectMapper = objectMapper;
  }

  public Object getEndpointBean() {
    return endpointBean;
  }

  public void setEndpointBean( Object endpointBean ) {
    this.endpointBean = endpointBean;
  }

  public ObjectMapper getObjectMapper() {
    return objectMapper;
  }

  public void setObjectMapper( ObjectMapper objectMapper ) {
    this.objectMapper = objectMapper;
  }

  public String getAddress() {
    return address;
  }

  public void setAddress( String address ) {
    this.address = address;
  }

  //OperatorWrap isn't helpful for autogenerated methods
  //CHECKSTYLE:OperatorWrap:OFF
  @Override public boolean equals( Object o ) {
    if ( this == o ) {
      return true;
    }
    if ( o == null || getClass() != o.getClass() ) {
      return false;
    }

    DocEndpointImpl that = (DocEndpointImpl) o;

    if ( address != null ? !address.equals( that.address ) : that.address != null ) {
      return false;
    }
    if ( endpointBean != null ? !endpointBean.equals( that.endpointBean ) : that.endpointBean != null ) {
      return false;
    }
    return !( objectMapper != null ? !objectMapper.equals( that.objectMapper ) : that.objectMapper != null );

  }

  @Override public int hashCode() {
    int result = address != null ? address.hashCode() : 0;
    result = 31 * result + ( endpointBean != null ? endpointBean.hashCode() : 0 );
    result = 31 * result + ( objectMapper != null ? objectMapper.hashCode() : 0 );
    return result;
  }

  @Override public String toString() {
    return "DocEndpointImpl{" +
      "address='" + address + '\'' +
      ", endpointBean=" + endpointBean +
      ", objectMapper=" + objectMapper +
      '}';
  }
  //CHECKSTYLE:OperatorWrap:ON
}
