/*!
 * PENTAHO CORPORATION PROPRIETARY AND CONFIDENTIAL
 *
 * Copyright 2002 - 2015 Pentaho Corporation (Pentaho). All rights reserved.
 *
 * NOTICE: All information including source code contained herein is, and
 * remains the sole property of Pentaho and its licensors. The intellectual
 * and technical concepts contained herein are proprietary and confidential
 * to, and are trade secrets of Pentaho and may be covered by U.S. and foreign
 * patents, or patents in process, and are protected by trade secret and
 * copyright laws. The receipt or possession of this source code and/or related
 * information does not convey or imply any rights to reproduce, disclose or
 * distribute its contents, or to manufacture, use, or sell anything that it
 * may describe, in whole or in part. Any reproduction, modification, distribution,
 * or public display of this information without the express written authorization
 * from Pentaho is strictly prohibited and in violation of applicable laws and
 * international treaties. Access to the source code contained herein is strictly
 * prohibited to anyone except those individuals and entities who have executed
 * confidentiality and non-disclosure agreements or other agreements with Pentaho,
 * explicitly covering such access.
 */

package com.pentaho.profiling.api.doc.rest;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

/**
 * Created by bryan on 4/6/15.
 */
public class DocEntry {
  private String message;
  private String returnDescription;
  private List<DocParameter> parameters;

  public DocEntry() {
    this( null, null, new ArrayList<DocParameter>() );
  }

  public DocEntry( String message, String returnDescription, List<DocParameter> parameters ) {
    this.message = message;
    this.returnDescription = returnDescription;
    this.parameters = parameters;
  }

  public String getMessage() {
    return message;
  }

  public void setMessage( String message ) {
    this.message = message;
  }

  public String getReturnDescription() {
    return returnDescription;
  }

  public void setReturnDescription( String returnDescription ) {
    this.returnDescription = returnDescription;
  }

  public List<DocParameter> getParameters() {
    return parameters;
  }

  public void setParameters( List<DocParameter> parameters ) {
    this.parameters = parameters;
  }

  //OperatorWrap isn't helpful for autogenerated methods
  //CHECKSTYLE:OperatorWrap:OFF
  @Override public boolean equals( Object o ) {
    if ( this == o ) {
      return true;
    }
    if ( o == null || getClass() != o.getClass() ) {
      return false;
    }

    DocEntry docEntry = (DocEntry) o;

    if ( message != null ? !message.equals( docEntry.message ) : docEntry.message != null ) {
      return false;
    }
    if ( returnDescription != null ? !returnDescription.equals( docEntry.returnDescription ) :
      docEntry.returnDescription != null ) {
      return false;
    }
    return !( parameters != null ? !parameters.equals( docEntry.parameters ) : docEntry.parameters != null );

  }

  @Override public int hashCode() {
    int result = message != null ? message.hashCode() : 0;
    result = 31 * result + ( returnDescription != null ? returnDescription.hashCode() : 0 );
    result = 31 * result + ( parameters != null ? parameters.hashCode() : 0 );
    return result;
  }

  @Override public String toString() {
    return "DocEntry{" +
      "message='" + message + '\'' +
      ", returnDescription='" + returnDescription + '\'' +
      ", parameters=" + parameters +
      '}';
  }
  //CHECKSTYLE:OperatorWrap:ON
}
